//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M_Inventory_Web_API_NEW_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Customer_Item_Invoice = new HashSet<Customer_Item_Invoice>();
            this.Supplier_Item_Invoice = new HashSet<Supplier_Item_Invoice>();
        }
    
        public int Id { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Code { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public Nullable<double> CostPrice { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<double> MRP { get; set; }
        public Nullable<int> StandardUnit_ID { get; set; }
        public Nullable<int> PurchaseUnit_ID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> PurchaseTax { get; set; }
        public Nullable<int> SalesTax { get; set; }
        public Nullable<int> OpeningStock { get; set; }
        public Nullable<int> IdealQuantity { get; set; }
        public Nullable<int> ReorderQuantity { get; set; }
        public Nullable<int> MaxQuantity { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<bool> AllowSales { get; set; }
        public Nullable<bool> AllowPurchase { get; set; }
        public Nullable<bool> AllowInword { get; set; }
        public Nullable<bool> AllowOutword { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ManufacturingDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> ProfitPercentage { get; set; }
        public Nullable<bool> Status { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public string extra3 { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Item_Invoice> Customer_Item_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Item_Invoice> Supplier_Item_Invoice { get; set; }
    }
}
